#!/usr/bin/env -S just --justfile

## repo configuration
sub-update:
  cd .. && git submodule update --init --recursive

## nix installation
install IP:
  ssh -o "StrictHostKeyChecking no" nixos@{{IP}} "sudo bash -c '\
    nix-shell -p git --run \"cd /root/ && \
    rm -rf nix-snippets && \
    git clone https://github.com/ryanbarrett/nix-snippets.git && \
    cd nix-snippets/2025-05-nix-test/nix/hosts/nixos/nix-test/ && \
    sh install-nix.sh\"'"

## Set your root password in the new instance
## ssh -o \"StrictHostKeyChecking no\" nixos@{{IP}}
## sudo su 
## nixos-enter --root /mnt 
## passwd

## nix updates
hostname := `hostname | cut -d "." -f 1`
[linux]
switch target_host=hostname:
  cd nix && sudo nixos-rebuild switch --flake .#{{target_host}}

## copy docker compose yaml to remote host via Ansible
#compose HOST *V:
#  cd ansible && ansible-playbook playbook.yaml --limit {{HOST}} --tags compose {{V}}

# remove old host key with: ssh-keygen -R {{IP}}  